apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-puls
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 40
  readiness:
    path: /internal/isReady
    initialDelay: 40
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 256Mi
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  kafka:
    pool: "{{ kafka_pool }}"
  env:
    - name: DB_DRIVER
      value: "org.postgresql.Driver"
    - name: AMPLITUDE_PROXY_BASE_URL
      value: "{{ amplitude_proxy_base_url }}"
  gcp:
    sqlInstances:
      - name: pam-puls
        type: POSTGRES_14
        tier: "{{ cloudsql_tier }}"
        diskType: SSD
        highAvailability: true
        diskSize: 20
        diskAutoresize: true
        databases:
          - name: puls
            envVarPrefix: DB
        cascadingDelete: false
  accessPolicy:
    outbound:
      external:
        - host: amplitude.com
        - host: reops-proxy.intern.nav.no
