apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "pam-puls-alerts"
  namespace: "teampam"
  labels:
    team: "teampam"
spec:
  groups:
    - name: "pam-puls-alerts"
      rules:
        - alert: "pam-puls har ikke kjørt ferdig batchjobb på mer enn ett døgn"
          expr: sum(increase(pam_puls_batch_success_total[1d])) < 1
          for: 1h
          annotations:
            consequence: "App {{ $labels.app }} i namespace {{ $labels.namespace }} har ikke kjørt ferdig batchjobb på mer enn ett døgn"
            action: "Sjekk loggene"
          labels:
            namespace: "teampam"
            severity: critical
