apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
  name: pam-puls-intern-2
  namespace: teampam
  labels:
    team: teampam
spec:
  pool: {{ kafka_pool }}
  config:
    cleanupPolicy: compact,delete
    minimumInSyncReplicas: 1
    partitions: 3
    replication: 2
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 168 #  7 days
  acl:
    - team: teampam
      application: pam-puls
      access: readwrite
    - team: teampam
      application: aiven-tuan
      access: readwrite
    - team: teampam
      application: pam-import-api
      access: read
    - team: teampam
      application: pam-stillingsregistrering-api
      access: read
    - team: teampam
      application: pam-kafka-manager
      access: read
