apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: pam-puls-intern-1
  namespace: teampam
  labels:
    team: teampam
spec:
  pool: {{ kafka_pool }}
  config:
    cleanupPolicy: compact,delete
    minimumInSyncReplicas: 1
    partitions: 3
    replication: 3
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 360 #  15 days
  acl:
    - team: teampam
      application: pam-puls
      access: readwrite   # read, write, readwrite
    - team: teampam
      application: aiven-tuan
      access: readwrite
