name: build-deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - main
      - legg_til_outbound

jobs:
  call-workflow:
    uses: navikt/pam-deploy/.github/workflows/deploy-dev.yml@v4
    with:
      NAIS_RESOURCE: naiserator.yml,topic.yaml
      JAVA_VERSION: "17"
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
