name: build-deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '14'
          cache: 'gradle'
      - name: build and test
        run: |
          ./gradlew clean build -x test
  call-workflow:
    uses: navikt/pam-deploy/.github/workflows/deploy-dev.yml@v2
